### ISSUE TITLE
Mark all articles as read fails

### ISSUE THREAD

**Issue by tigre-bleu** [Huessenbergnetz/Fuoten#40]
in the pseudo folder "All articles" using pulley menu and selecting "Mark all as read" launches the remorse timer. However, when it reaches "0", it remains displayed like this forever and read status is not updated.

**Comment by tigre-bleu** [comment]
Any progress on this? I noticed that it is possible to mark a complete folder as read without problem. It is just the "All articles" folder that has problems.

**Comment by buschmann23** [comment]
I will for now remove this action from the page, as this depends on Huessenbergnetz/libfuoten#47. I first need to improve the marking of items, because currently all marked items are transferred as single items - what might take a long time on server side to process.

**Comment by tigre-bleu** [comment]
Working for me with the workaround. :+1:
