### ISSUE TITLE
Option for navigating back after marking feed as read

### ISSUE THREAD

**Issue by buschmann23** [Huessenbergnetz/Fuoten#47]
Add an switchable option that activates the following behavior as proposed by [paolomi](https://openrepos.net/comment/27467#comment-27467):

> when I select "mark as read /unread" from pull-down menu, I'd like fuoten goes back to the previous page

**Comment by paolomi** [comment]
Hi :) The same feature described above (pagestack.navigateBack) is useful also when I select:
- (pull down menu) Add to favorites / Remove from favorites
- (pull down menu) Mark feed read
- (pull down menu) Mark folder read

That's all. Many thanks!
