### ISSUE TITLE
GTK version for desktop and librem5 smartphone

### ISSUE THREAD

**Issue by tigre-bleu** [Huessenbergnetz/Fuoten#49]
I know that this this is a long shot and a lot of work to do, but as the [Librem5](https://puri.sm/products/librem-5/) phone is getting closer, I would be nice to have a fuoten interface using GTK.

Librem5 is a Linux phone with a regular linux distribution, using Gnome as a default desktop.

A GTK widget called [LibHandy](https://source.puri.sm/Librem5/libhandy) has been created to make app compatible both for Desktop and Smartphone form factors.

**Comment by buschmann23** [comment]
Hm. Currently the only thing I planned beside the SailfishOS version is a UI version for KDE/Kirigami. Personally I have no plans to look into and learn GTK. But if someone is willing to contribute such UI, I am open for it. But as libfuoten is also based on Qt, all have to be rewritten, at least if there should be no Qt. So, currently really no option for me.
