### ISSUE TITLE
Problems setting up Fuoten in SailfishOS SDK

### ISSUE THREAD

**Issue by jgibbon** [Huessenbergnetz/Fuoten#55]
Hi,
while setting up Fuoten in the SailfishOS SDK, I got aware of some very minor issues that may be a problem for some people trying the same:
 - The readme doesn't mention the needed qmake argument AES256_KEY. 
Also, the icons creation isn't mentioned but apparently needed for successful compilation.
 - libfuoten requires sqlite3, but there's no `BuildRequires:  pkgconfig(sqlite3)` in the Fuoten .spec file. (Not sure if this is a libfuoten issue, but as far as I've seen, there's no spec over there.)

Also, I'm not really aware how to manage/add _new_ translation strings, but that may just be my missing knowledge of how the Qt language tools work outside of the SDK itself (or my setup is a bit broken). Not a big problem, though, since I seem to be unable to add a "next article" PushUp-MenuItem that doesn't crash the application after a few articles anyway. And even if that worked reliably, I doubt that my "[solution](https://github.com/jgibbon/Fuoten/commit/bc13b92c84e4e1d8504772c8e3570e317a82fb63)" would meet any quality requirements for a PR.

That being said, thanks for creating Fuoten, it is really, really useful!

**Comment by buschmann23** [comment]
Thanks for the hints. :) I fixed the issue with the missing sqlit3 in the spec file and improved the SailfishOS build instructions and code setup infrastructure.

Translations are managed via [Transifex](https://www.transifex.com/huessenbergnetz/fuoten/) as mentioned in the [CONTRIBUTING.md](https://github.com/Huessenbergnetz/Fuoten/blob/master/CONTRIBUTING.md).

I will have a look into your code when I have a bit more time. :)
