### ISSUE TITLE
New articles no longer show up

### ISSUE THREAD

**Issue by sonologic** [Huessenbergnetz/Fuoten#64]
A few days ago, when synchronising new articles will no longer show up. I do get a notification that new articles were downloaded ('Successfully requested articles from the server. There are 5 new unread articles.'), but the articles simply do not show up in the views, all feeds show 0 unread articles and are stuck on the last article requested a few days ago.

I did upgrade nextcloud from 19.x to 20.x over the past weekend, so that might be related (but it might also be a coincidence). I will try to get some more information (ie, output from the process) and update this ticket, but perhaps this already rings a bell to someone.

**Comment by sonologic** [comment]
I looked at the database (/home/defaultuser/.local/share/harbour-fuoten/harbour-fuoten/database.sqlite) and the newer items are not in there either.

**Comment by sonologic** [comment]
Uninstalled, wiped /home/defaultuser/.local/share/harbour-fuoten and it seems articles are coming in again.

**Comment by buschmann23** [comment]
What version of Fuoten and News app are you using? I am on Nextcloud 20.0.4 and News app 15.1.0. Together with Fuoten 0.7.1 I have no issues.

**Comment by sonologic** [comment]
Nextcloud 20.0.3, News app 15.1.0, fuoten is now at 0.7.1, i didn't think to check what it was before I uninstalled. Maybe it was an older version, although I did update all apps from all stored yesterday.

It seems it is working again, i'll wait for some more new articles to come in to the server to make sure it's back to normal now, and if that is the case close this ticket.

**Comment by buschmann23** [comment]
I think you had a version older than Fuoten 0.7.1 because that version fixed a badly documented change in the News app API. See also https://github.com/Huessenbergnetz/Fuoten/issues/63 .

**Comment by sonologic** [comment]
Indeed, new articles are coming in again. Appears indeed I still had an older version. Apologies for the noise!
