### ISSUE TITLE
Generate PNGs at build

### ISSUE THREAD

**Issue by Thaodan** [Huessenbergnetz/Fuoten#72]
Currently icons have to be generate separate which taints the build makes it non reproduce-able. 
If the conversion is done it build time this is solved.
If we use SailfishOS to get the python3-cairosvg we can use that to generate the icons at build time (partialy already done in https://github.com/Huessenbergnetz/HBN_SFOS_Components/issues/1)

See here for reference how to generate icons:
+ https://github.com/communi/communi-sailfish/blob/master/data/data.pro (its qmake but could work similar in cmake)

Python3-Cairosvg in chum:
+ https://github.com/sailfishos-chum/python3-cairosvg
+ https://build.sailfishos.org/package/show/sailfishos:chum/python3-cairosvg

**Comment by buschmann23** [comment]
Will implement this when switching to CMake.
